apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-job
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              command: {{ .Values.cronjob.command }}
          restartPolicy: OnFailure